export const favoriteThings = [
    "when trump's old tweets bite him in the butt now that he's president",
    "annie's mac and cheese, no matter what time of day",
    "coffee, the fancy kind",
    "airplane bloody mary's",
    "the hotel balcony beer when you first arrive",
    "running in the rain",
    "georgia o'keffee's claiming innocence till the day she died",
    "sol lewitt precision",
    "grumpy cat (r.i.p)",
    "autotuned cats meowing on youtube",
    "Harry Style's cover of Juice",
    "early kanye, late outkast",
    "yerba mate from the gourd",
    "the hidden arrow in the fedex logo",
    "showing up early for the movie previews",
    "beach volleyball",
    "parallel parking with small cars",
    "soggy/soft life savers",
    "people with good laughs",
    "dogs that just want to say hi",
    "cats that play fetch",
    "google commercials that make you cry",
    "the first day after the last day of my period",
    "collecting gadgets that flopped (amazon fire, anyone?)",
    "youtube (there isn't a youtube video I haven't seen)",
    "plants that don't need a lot of water",
    "the false sense of craftmanship I get from putting together ikea furniture",
    "matisse' the dancers'",
    "taiki waititi",
    "richard feynman",
    "edie windsor",
    "sweden in the summertime",
    "graduation speeches",
    "pizza rat...somehow no matter what mood I am in, I can relate to pizza rat",
    "dogs with cute eyebrows",
    "next-day microwaved pizza",
    "classic ice cream sandwiches",
    "jimi hendrix at woodstock",
    "the 8 minute abs workout that you can still find on youtube",
    "enthusiasm",
    "joie de vivre",
    "craft brewery beer can labels",
    "the perfect emoji",
    "an empty trader joes"
  ];